### ISSUE TITLE
Matrix Space

### ISSUE THREAD

**Issue by itsmeboy0** [ReVancedTeam/revanced-suggestions#1]
Not sure if this is the place to open up this issue, but other than the [Discord Server](https://discord.gg/revanced), it would be beneficial if a [Matrix](https://matrix.org/) Space bridged to Discord is available for people who don't want to use Discord (FOSS/Privacy users and the like), and in case the server gets taken down there is a backup.

**Comment by oSumAtrIX** [comment]
#revanced:matrix.org

**Comment by itsmeboy0** [comment]
> #revanced:matrix.org

Not a matrix space but thanks
