### ISSUE TITLE
refresh your home page without limit

### ISSUE THREAD

**Issue by techno-arch** [ReVancedTeam/revanced-suggestions#100]
On older versions of yt i could refresh the home page as much as i wanted but now i have to wait to do it

**Comment by oSumAtrIX** [comment]
Refreshing the home page works without any issue. Please elaborate

**Comment by techno-arch** [comment]
https://youtu.be/tsd7zqesd4s
After i refresh it once it wont let me do it again for some time

**Comment by oSumAtrIX** [comment]
This is an error on your side. You can refresh multiple times.

**Comment by CnC-Robert** [comment]
I think its a bug of vanced where if you remove something from the homepage you can no longer pull down to refresh
