### ISSUE TITLE
Allow for TV/Movie Purchases

### ISSUE THREAD

**Issue by iiKromium** [ReVancedTeam/revanced-suggestions#102]
Whenever you try to buy a movie or TV show in Vanced, the page will fail to redirect or the purchase just won't go through. Would be nice if this could be fixed in Revanced.

**Comment by DraakjeYoblama** [comment]
This might be fixed by default since Revanced will work differently

**Comment by oSumAtrIX** [comment]
For now this issue does not exist. Please reopen if it does.
