### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by Ga13Ou** [ReVancedTeam/revanced-suggestions#106]
Hello,

Will Revanced be available for Iphone (IOS) users?
That's cool if this could be the case.

**Comment by YTCoolioMan** [comment]
Probably not. Apple devices have been known to be quite... difficult with custom apps and downloading non-apple approved apps.

but idk maybe the revanced devs are wizards

**Comment by Canny1913** [comment]
> Probably not. Apple devices have been known to be quite... difficult with custom apps and downloading non-apple approved apps.
> 
> but idk maybe the revanced devs are wizards

even if they did made one only jail-broken users would be able to install that since you can only install unsigned apps for 7 days on normal IOS

**Comment by oSumAtrIX** [comment]
ReVanced is made for Android

**Comment by ps1-hagrid** [comment]
Also uYouPlus.
