### ISSUE TITLE
Do not make any NFT 

### ISSUE THREAD

**Issue by rafagale** [ReVancedTeam/revanced-suggestions#11]
Please do not make any NFT about this. 

Kind regards

**Comment by oSumAtrIX** [comment]
Check the faq channel on our Discord server.

**Comment by baiorett** [comment]
minting 109019109 revanced nfts brrrrrr 🥶

**Comment by oSumAtrIX** [comment]
> this is a joke

https://github.com/ReVancedTeam/revanced-suggestions/issues/5#issuecomment-1079767422
