### ISSUE TITLE
Make ReVanced manager open-source :)

### ISSUE THREAD

**Issue by protonmailtp** [ReVancedTeam/revanced-suggestions#2]
It would just speed up the process and we can contribute.

**Comment by DraconicNEO** [comment]
I think this project is actually intended to be open source, everything is applied via patches to the app.

**Comment by oSumAtrIX** [comment]
> It would just speed up the process and we can contribute.

It will be. The reason it isn't, is because most of the manager's codebase is subject to change, which is why contributions are mostly impossible/useless. When we think, it's in a state we can continue to work on with the community, we will be. Thanks
