### ISSUE TITLE
Create better instuctions on installing thru Android CLI OR: have an .apk available to DL.

### ISSUE THREAD

**Issue by Gilgamesh0028** [ReVancedTeam/revanced-suggestions#29]
A few users in a discord I'm in have complained about not being able to understand the instructions, and were unable to install, due to PEBKAC. I suggest a easily install-able .APK to circumvent the issue of PEBKAC'able users.

**Comment by MulverineX** [comment]
The point of Revanced is to *not* redistribute patched YouTube files, distinguishing it legally from Vanced. The manager is required for this project so the patching happens on the user's machine.

**Comment by Aioht** [comment]
But I want to understand how to install, is there a video and something else?

**Comment by oSumAtrIX** [comment]
ReVanced is not done yet, please wait in our official Discord Server for updates.
