### ISSUE TITLE
Allow downloading videos to external storage and share locally

### ISSUE THREAD

**Issue by bhaskarvilles** [ReVancedTeam/revanced-suggestions#32]
- It is very clear that downloading videos from youtube is a war..
- Vanced app developers dosen't think about the downloading option just because of the stock YT user Experience feel.
- i'm proposing A downloadable videos with sharing capabilities with in local devices would be better.
- It was done by adding a feature to downloaded content in youtube can be directly shared externally.

**Comment by oSumAtrIX** [comment]
Dupe of #14
