### ISSUE TITLE
"Add to queue"

### ISSUE THREAD

**Issue by D3XX3R** [ReVancedTeam/revanced-suggestions#35]
On the regular website you can add videos to a queue. This is not possible on the mobile app and also wasn't possible with Vanced.

**Comment by GreenMan36** [comment]
Note for people interested in implementing; it might be useful to know that for casting there is a full queue system.

**Comment by Lucaskyy** [comment]
How does the queue system work on YouTube Desktop? Could you share some images?

Normally I would check myself, but I'm currently unable to :p

**Comment by D3XX3R** [comment]
You click on the three dots next to a video and press "Add to queue"
![____________________ (1)](https://user-images.githubusercontent.com/48421663/160852249-a3799d5f-997a-4e17-b888-ea73499e65c8.png)

After you've added some videos you can click on the small picture-in-picture window to open the watch page and there you'll find the queue on the right side. It kinda looks like a playlist.
![____________________ (2)](https://user-images.githubusercontent.com/48421663/160852509-8459f215-0532-4b6b-80ca-ec9629ce9d5a.png)

After you've seen a video it will automatically start playing the next one.

**Comment by insanitywanted** [comment]
+1

**Comment by oSumAtrIX** [comment]
You can create a playlist, or add videos to the default watch later playlist and then play through that one, no need for a seperate queueing system

**Comment by D3XX3R** [comment]
I personally think the queue feature would be a nice feature to have. Watch later (at least for me) has always been a broad collection of a lot of videos. With a queue you could pick out some of these videos to watch and remove them when you've seen them.

**Comment by oSumAtrIX** [comment]
Create a queue playlist then?

**Comment by Lucaskyy** [comment]
I do agree that some people may find it useful, but if we do add this it will be very low priority since this is already possible with a workaround.

**Comment by MSOB7YY** [comment]
anyone who is eager for queue feature, u can use YMusic for now ;>

**Comment by nochlab1** [comment]
+1
