### ISSUE TITLE
Shorts to Normal YouTube video quick button 

### ISSUE THREAD

**Issue by TickingTime** [ReVancedTeam/revanced-suggestions#48]
A button in the YouTube shorts... Shorts that quick swaps to the same video but not a short. Eg. 
https://youtube.com/shorts/dLJlkSMDZFQ
Would become 
https://youtube.com/v/dLJlkSMDZFQ And it would open the normal video instead when pushing the button.
![IMG_20220330_220528_e](https://user-images.githubusercontent.com/18560509/160980716-860a014c-0a00-4b3b-8fa6-9bea6ee7de02.png)
Could look something like this I guess if you need a physical example of my idea... Just badly

**Comment by lewis1277** [comment]
this would be really handy. Shorts for some reason don't cast when you go into them and are connected to a TV and have no cast button in them, so I have to manually switch them to normal videos which is annoying

**Comment by bappitybup** [comment]
sorry wrong account from my other post

this would be really handy. Shorts for some reason don't cast when you go into them and are connected to a TV and have no cast button in them, so I have to manually switch them to normal videos which is annoying

**Comment by Sadaweya0** [comment]
But could there be an automated convertion so like I don't have to click that button all the time but instead I can switch shorts on/off in settings and clicking on any short would act like any other video.

**Comment by Lucaskyy** [comment]
@Sadaweya0 Please move to #9
