### ISSUE TITLE
Add HeatSeeker

### ISSUE THREAD

**Issue by autergame** [ReVancedTeam/revanced-suggestions#53]
Only avaliable to premium or some of discord users.
https://beebom.com/youtube-heatseeker-highlight-most-watched-parts-video/

![image](https://user-images.githubusercontent.com/24947356/161175610-c9a585ec-0359-4b69-bf47-386230a233c5.png)
![image](https://user-images.githubusercontent.com/24947356/161175764-149ad3b4-afc0-46bd-914f-cea91dfa1b64.png)

**Comment by oSumAtrIX** [comment]
The api will probably restrict this, sorry
