### ISSUE TITLE
Block channels and individual videos from both recommendations and search results, using IDs or keywords

### ISSUE THREAD

**Issue by PeteAnd** [ReVancedTeam/revanced-suggestions#60]
The browser extension _blocktube_ is a perfect example of the implementation: https://github.com/amitbl/blocktube
It allows you to block entire channels, videos and even comments. Given the amount of trash that's on YT I honestly can't live without it. 

I personally block a long list of popular channels that I hate and that would otherwise pop up all the time on my screen.  

Example of a major quality of life improvement: use keywords like "reacts to" or "reaction to" to get rid of the retarded reaction videos that infest the search results for some topics.

**Comment by unofficialdev** [comment]
This is also a feature I've always wanted to have. there's so much malicious, unhealthy content that I don't want it to appear in suggestions and search results. it would be nice if this feature was implemented

**Comment by oSumAtrIX** [comment]
Dupe of #41

**Comment by unofficialdev** [comment]
> Dupe của [# 41](https://github.com/ReVancedTeam/revanced-suggestions/issues/41)

you should close #41 instead of this

**Comment by PeteAnd** [comment]
> > Dupe của [# 41](https://github.com/ReVancedTeam/revanced-suggestions/issues/41)
> 
> You should close #41 instead of this. Because this one is more complete.

I agree

**Comment by oSumAtrIX** [comment]
No, you should continue and add everything you want on #41
