### ISSUE TITLE
Old YouTube UI

### ISSUE THREAD

**Issue by fym35** [ReVancedTeam/revanced-suggestions#66]
An ootion to toggle the old youtube ui that it used to have in v.15.43 (2020)

like this:
![Screenshot_20220404_074433](https://user-images.githubusercontent.com/57803365/161481163-fb24d159-e3e5-411d-96ef-cdb93f907f73.jpg)
![IMG_20220404_074142](https://user-images.githubusercontent.com/57803365/161480976-afd9d73d-cb39-42e2-99c0-dd4ac9f289b4.jpg)

**Comment by zaourzag** [comment]
I have one word to say: yes. Also blue like button

**Comment by MSOB7YY** [comment]
[this](https://github.com/ReVancedTeam/revanced-suggestions/issues/37#issue-1185660820) would be a lot better
