### ISSUE TITLE
Some problems on viki...

### ISSUE THREAD

**Issue by artemisluck97** [ReVancedTeam/revanced-suggestions#79]
when I use it to download viki videos, it doesn't work. Is it still available on Rakuten Viki?

It goes like this:

D:\Program Files (x86)\windows YT-DLP 2021\Windows1229_3>yt-dlp.exe https://www.viki.com/videos/1193039v

[viki] 1193039v: Downloading video JSON

[viki] 1193039v: Downloading video streams JSON

[viki] 1193039v: Downloading initial MPD manifest

[viki] 1193039v: Downloading MPD manifest

WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them

ERROR: [viki] 1193039v: Requested format is not available. Use --list-formats for a list of available formats

Could you plz fix it? I cannot download video from viki now and I really need that...

**Comment by Lucaskyy** [comment]
This is not yt-dlp support.
