### ISSUE TITLE
Stretch to fit instead of zoom to fit

### ISSUE THREAD

**Issue by sargeeva** [ReVancedTeam/revanced-suggestions#88]
Having the ability to stretch the video to fit screens with weird aspect ratios *cough* samsung *cough* instead of the weird zoom to fit screen.

**Comment by Relected** [comment]
wouldn't that make the video ugly?

**Comment by sargeeva** [comment]
Definitely not, and watching with it zoomed to fill the screen makes the video look ugly and not having the black bars cause burn in is ideal.

**Comment by boehs** [comment]
Duplicate of #4
